Import Library

In [1]:
import pandas as pd
import numpy as np

Load Dataset

In [2]:
df = pd.read_csv("../data/extracted/orders_extracted.csv")

df.head()

,order_id,total_qty,total_weight_gr,total_returned_qty,total_discount,product_categories,num_product_categories,order_status,cancellation_reason,shipping_option,payment_method,city,province,shipping_paid_by_buyer,estimated_shipping_discount,total_payment,estimated_shipping_cost,order_created_at,source_file
0,ORD_0000001,2,2000,0,0,Celengan,1,Selesai,NaN,Reguler (Cashless)-SPX Standard,Saldo ShopeePay,KOTA SERANG,BANTEN,0,10000,38300,10000,2024-04-01 00:15,AprilSales2024.xlsx
1,ORD_0000002,1,500,0,0,Celengan,1,Selesai,NaN,Hemat Kargo-SPX Hemat,COD (Bayar di Tempat),KOTA SEMARANG,JAWA TENGAH,0,14500,18576,14500,2024-04-01 01:47,AprilSales2024.xlsx
2,ORD_0000003,1,500,0,0,Celengan,1,Selesai,NaN,Hemat Kargo-SPX Hemat,SeaBank Bayar Instan,KAB. BOGOR,JAWA BARAT,0,8000,7069,8000,2024-04-01 04:25,AprilSales2024.xlsx
3,ORD_0000004,2,400,0,0,Mangkok Sambal / Saus,1,Selesai,NaN,Hemat Kargo-SPX Hemat,COD (Bayar di Tempat),KOTA JAMBI,JAMBI,0,20000,32200,20000,2024-04-01 04:41,AprilSales2024.xlsx
4,ORD_0000005,3,3600,0,0,"Keranjang, Other, Tempat Nasi",3,Batal,Dibatalkan oleh Pembeli. Alasan: Ubah Pesanan ...,Hemat Kargo-SPX Hemat,COD (Bayar di Tempat),KOTA TANGERANG,BANTEN,0,0,0,8000,2024-04-01 06:12,AprilSales2024.xlsx

In [3]:
df.shape

(20848, 19)

Basic Dataset Info

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 20848 entries, 0 to 20847
Data columns (total 19 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   order_id                     20848 non-null  str
 1   total_qty                    20848 non-null  int64
 2   total_weight_gr              20848 non-null  int64
 3   total_returned_qty           20848 non-null  int64
 4   total_discount               20848 non-null  int64
 5   product_categories           20848 non-null  str
 6   num_product_categories       20848 non-null  int64
 7   order_status                 20848 non-null  str
 8   cancellation_reason          2830 non-null   str
 9   shipping_option              20848 non-null  str
 10  payment_method               20848 non-null  str
 11  city                         20848 non-null  str
 12  province                     20848 non-null  str
 13  shipping_paid_by_buyer       20848 non-null  int64
 14  estimated_shipping_discount  20848 non-null  int64
 15  total_payment                20848 non-null  int64
 16  estimated_shipping_cost      20848 non-null  int64
 17  order_created_at             18868 non-null  str
 18  source_file                  20848 non-null  str
dtypes: int64(9), str(10)
memory usage: 5.9 MB

In [5]:
df.head()

,order_id,total_qty,total_weight_gr,total_returned_qty,total_discount,product_categories,num_product_categories,order_status,cancellation_reason,shipping_option,payment_method,city,province,shipping_paid_by_buyer,estimated_shipping_discount,total_payment,estimated_shipping_cost,order_created_at,source_file
0,ORD_0000001,2,2000,0,0,Celengan,1,Selesai,NaN,Reguler (Cashless)-SPX Standard,Saldo ShopeePay,KOTA SERANG,BANTEN,0,10000,38300,10000,2024-04-01 00:15,AprilSales2024.xlsx
1,ORD_0000002,1,500,0,0,Celengan,1,Selesai,NaN,Hemat Kargo-SPX Hemat,COD (Bayar di Tempat),KOTA SEMARANG,JAWA TENGAH,0,14500,18576,14500,2024-04-01 01:47,AprilSales2024.xlsx
2,ORD_0000003,1,500,0,0,Celengan,1,Selesai,NaN,Hemat Kargo-SPX Hemat,SeaBank Bayar Instan,KAB. BOGOR,JAWA BARAT,0,8000,7069,8000,2024-04-01 04:25,AprilSales2024.xlsx
3,ORD_0000004,2,400,0,0,Mangkok Sambal / Saus,1,Selesai,NaN,Hemat Kargo-SPX Hemat,COD (Bayar di Tempat),KOTA JAMBI,JAMBI,0,20000,32200,20000,2024-04-01 04:41,AprilSales2024.xlsx
4,ORD_0000005,3,3600,0,0,"Keranjang, Other, Tempat Nasi",3,Batal,Dibatalkan oleh Pembeli. Alasan: Ubah Pesanan ...,Hemat Kargo-SPX Hemat,COD (Bayar di Tempat),KOTA TANGERANG,BANTEN,0,0,0,8000,2024-04-01 06:12,AprilSales2024.xlsx

In [6]:
df.columns

Index(['order_id', 'total_qty', 'total_weight_gr', 'total_returned_qty',
       'total_discount', 'product_categories', 'num_product_categories',
       'order_status', 'cancellation_reason', 'shipping_option',
       'payment_method', 'city', 'province', 'shipping_paid_by_buyer',
       'estimated_shipping_discount', 'total_payment',
       'estimated_shipping_cost', 'order_created_at', 'source_file'],
      dtype='str')

Missing Value Check

In [17]:
missing_values = df.isnull().sum().sort_values(ascending=False)
missing_values

cancellation_reason            18018
order_created_at                1980
order_id                           0
total_weight_gr                    0
total_qty                          0
product_categories                 0
total_returned_qty                 0
num_product_categories             0
order_status                       0
shipping_option                    0
total_discount                     0
payment_method                     0
city                               0
shipping_paid_by_buyer             0
province                           0
estimated_shipping_discount        0
total_payment                      0
estimated_shipping_cost            0
source_file                        0
dtype: int64

Duplicate Data Check

In [11]:
df.duplicated().sum()

np.int64(0)

Order Status Validation

In [14]:
df["order_status"].value_counts()

order_status
Selesai                                                                                   17768
Batal                                                                                      2830
Sedang Dikirim                                                                               59
Pesanan diterima, namun Pembeli masih dapat mengajukan pengembalian hingga 2025-12-08.       38
Pesanan diterima, namun Pembeli masih dapat mengajukan pengembalian hingga 2025-12-06.       34
Pesanan diterima, namun Pembeli masih dapat mengajukan pengembalian hingga 2025-12-07.       34
Telah Dikirim                                                                                30
Pesanan diterima, namun Pembeli masih dapat mengajukan pengembalian hingga 2025-12-05.       25
Pesanan diterima, namun Pembeli masih dapat mengajukan pengembalian hingga 2025-12-09.       22
Pesanan diterima, namun Pembeli masih dapat mengajukan pengembalian hingga 2025-12-10.        6
Pesanan diterima, namun Pembeli masih dapat mengajukan pengembalian hingga 2025-12-11.        2
Name: count, dtype: int64

Numeric Data Type Convert

In [15]:
numeric_cols = [
    "total_qty",
    "total_weight_gr",
    "total_returned_qty",
    "total_discount",
    "num_product_categories",
    "shipping_paid_by_buyer",
    "estimated_shipping_discount",
    "total_payment",
    "estimated_shipping_cost"
]

for col in numeric_cols:
    df[col] = pd.to_numeric(df[col], errors="coerce")

In [16]:
df[numeric_cols].info()

<class 'pandas.DataFrame'>
RangeIndex: 20848 entries, 0 to 20847
Data columns (total 9 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   total_qty                    20848 non-null  int64
 1   total_weight_gr              20848 non-null  int64
 2   total_returned_qty           20848 non-null  int64
 3   total_discount               20848 non-null  int64
 4   num_product_categories       20848 non-null  int64
 5   shipping_paid_by_buyer       20848 non-null  int64
 6   estimated_shipping_discount  20848 non-null  int64
 7   total_payment                20848 non-null  int64
 8   estimated_shipping_cost      20848 non-null  int64
dtypes: int64(9)
memory usage: 1.4 MB

Date Data Type Convert

In [18]:
df["order_created_at"] = pd.to_datetime(df["order_created_at"], errors="coerce")

In [19]:
df["order_created_at"].isnull().sum()

np.int64(1980)

In [20]:
df["order_created_at"].min(), df["order_created_at"].max()

(Timestamp('2023-12-01 00:33:00'), Timestamp('2025-11-30 23:17:00'))

In [21]:

df["order_month"] = df["order_created_at"].dt.to_period("M").astype(str)

In [22]:
df["order_month"].value_counts(dropna=False).sort_index()

order_month
2023-12     444
2024-01     431
2024-02     389
2024-03     453
2024-04     492
2024-05     620
2024-06     697
2024-07    1270
2024-08    1293
2024-09    1123
2024-10    1217
2024-11    1037
2025-01    1150
2025-02     957
2025-03     628
2025-04     824
2025-05     819
2025-06     615
2025-08     942
2025-09    1131
2025-10    1205
2025-11    1131
NaN        1980
Name: count, dtype: int64

Recover Missing Order Month from Source File

In [23]:
month_map = {
    "January": "01",
    "February": "02",
    "March": "03",
    "April": "04",
    "May": "05",
    "June": "06",
    "July": "07",
    "August": "08",
    "September": "09",
    "October": "10",
    "November": "11",
    "December": "12"
}

def extract_month_from_source(source_file):
    if pd.isna(source_file):
        return np.nan
    
    source_file = str(source_file)
    
    for month_name, month_num in month_map.items():
        if month_name in source_file:
            year = ''.join([char for char in source_file if char.isdigit()])
            if len(year) >= 4:
                return f"{year[:4]}-{month_num}"
    
    return np.nan

In [24]:
df["order_month_from_source"] = df["source_file"].apply(extract_month_from_source)

df["order_month"] = df["order_month"].replace("NaT", np.nan)
df["order_month"] = df["order_month"].fillna(df["order_month_from_source"])

In [25]:
df["order_month"].isnull().sum()

np.int64(0)

Data Quality Validation

Negative payment

In [26]:
df[df["total_payment"] < 0].shape[0]

0

Zero payment by status

In [27]:
df[df["total_payment"] == 0]["order_status"].value_counts()

order_status
Batal      2830
Selesai      62
Name: count, dtype: int64

Invalid quantity

In [28]:
df[(df["total_qty"].isnull()) | (df["total_qty"] <= 0)].shape[0]

0

Missing important columns

In [29]:
important_cols = [
    "order_id",
    "order_status",
    "product_categories",
    "payment_method",
    "shipping_option",
    "city",
    "province",
    "total_payment",
    "order_month"
]

df[important_cols].isnull().sum()

order_id              0
order_status          0
product_categories    0
payment_method        0
shipping_option       0
city                  0
province              0
total_payment         0
order_month           0
dtype: int64

Text Column Standardization

In [30]:
text_cols = [
    "product_categories",
    "order_status",
    "cancellation_reason",
    "shipping_option",
    "payment_method",
    "city",
    "province",
    "source_file"
]

for col in text_cols:
    df[col] = df[col].astype("string").str.strip()

Create Cleaned Dataset

In [31]:
cleaned_orders = df.copy()

In [32]:
cleaned_orders.shape

(20848, 21)

In [33]:
cleaned_orders.info()

<class 'pandas.DataFrame'>
RangeIndex: 20848 entries, 0 to 20847
Data columns (total 21 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   order_id                     20848 non-null  str
 1   total_qty                    20848 non-null  int64
 2   total_weight_gr              20848 non-null  int64
 3   total_returned_qty           20848 non-null  int64
 4   total_discount               20848 non-null  int64
 5   product_categories           20848 non-null  string
 6   num_product_categories       20848 non-null  int64
 7   order_status                 20848 non-null  string
 8   cancellation_reason          2830 non-null   string
 9   shipping_option              20848 non-null  string
 10  payment_method               20848 non-null  string
 11  city                         20848 non-null  string
 12  province                     20848 non-null  string
 13  shipping_paid_by_buyer       20848 non-null  int64
 14  estimated_shipping_discount  20848 non-null  int64
 15  total_payment                20848 non-null  int64
 16  estimated_shipping_cost      20848 non-null  int64
 17  order_created_at             18868 non-null  datetime64[us]
 18  source_file                  20848 non-null  string
 19  order_month                  20848 non-null  str
 20  order_month_from_source      20848 non-null  str
dtypes: datetime64[us](1), int64(9), str(3), string(8)
memory usage: 6.2 MB

Separate Completed and Cancelled Orders

In [34]:
completed_orders = cleaned_orders[cleaned_orders["order_status"] == "Selesai"].copy()
cancelled_orders = cleaned_orders[cleaned_orders["order_status"] == "Batal"].copy()

In [35]:
completed_orders.shape, cancelled_orders.shape

((17768, 21), (2830, 21))

Export

In [37]:
cleaned_orders.to_csv("../data/processed/cleaned_orders.csv", index=False)
completed_orders.to_csv("../data/processed/completed_orders.csv", index=False)
cancelled_orders.to_csv("../data/processed/cancelled_orders.csv", index=False)

Data Cleaning Summary

The extracted dataset was cleaned and validated before analysis. The cleaning process included:

- Checking missing values across key columns
- Checking duplicate rows and duplicate order IDs
- Converting numeric columns into proper numeric data types
- Converting order date into datetime format
- Creating `order_month` for monthly revenue analysis
- Recovering missing order month values from `source_file`
- Standardizing text columns by removing extra spaces
- Separating completed orders and cancelled orders for different analysis purposes

Completed orders are used for revenue analysis, while cancelled orders are analyzed separately to understand cancellation patterns.